trigger:
- accurics_x0wux7yd

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    terraform version
    echo Downloading accurics cli
    wget https://downloads.accurics.com/cli/latest/accurics_linux -O accurics 
    chmod +x accurics
    export ARM_SUBSCRIPTION_ID=82625fe6-8f75-4d80-b0c3-41badfcdee65
    export ARM_TENANT_ID=~q_Fayqnogi_1I51rf4b7r4MUka_0v3JsJ
    export ARM_CLIENT_ID=1b25d708-64d9-43ca-a6d4-7210952163ef
    export ARM_CLIENT_SECRET=734613be-a4f0-4fe5-9131-17614a0c896b
    echo Running accurics init...
    ./accurics init
    echo Running accurics plan...
    ./accurics plan
  displayName: 'download cli, run accurics init, run accurics plan'
